version: "3.7"
services:
  demo_web_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - seq_server
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      SerilogSeqServerUrl: "http://seq_server:80"
    volumes:
      - C:\Logs\DemoAppWeb:/app/Logs
  seq_server:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: Y
    restart: unless-stopped
    volumes:
      - C:\Logs\DemoAppWeb\SeqData:/data